name: Test
on:
  - pull_request
  - push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - uses: actions/checkout@v2
      - run: pnpx lockfile-lint --path package-lock.json --validate-https
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - uses: actions/checkout@v2
      - run: pnpm install
      - run: pnpm test
